### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yumoto34492** [yumoto34492/furima-34492#9]
#URL
https://furima-34492.herokuapp.com/

#Basic認証
- ID : furimatarou
- Password  : 34492

#出品者用
- email : itirou@itirou
- password : itirou34492

#8 購入者用
- email : jirou@jirou
- password : jirou34492

**Comment by snkw-works** [comment]
@yumoto34492 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/110751642-7f210b80-8287-11eb-8707-2eb42755b44f.png)

**Comment by yumoto34492** [comment]
ご確認ありがとうございます！
